# Generated by Django 4.2.7 on 2024-03-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='category',
        ),
        migrations.RemoveField(
            model_name='command',
            name='command_date',
        ),
        migrations.RemoveField(
            model_name='command',
            name='command_status',
        ),
        migrations.AddField(
            model_name='command',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='phone',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='street',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='zip',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
