# Generated by Django 4.2.7 on 2024-03-20 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('command', '0002_remove_command_category_remove_command_command_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='user',
            field=models.ForeignKey(default='user.id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
