# Generated by Django 4.2.7 on 2024-03-04 22:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('description', models.TextField(default='')),
                ('thumbnail', models.ImageField(upload_to='media')),
                ('publish', models.DateField(default=datetime.datetime(2024, 3, 4, 22, 1, 37, 645590))),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('promo', models.CharField(choices=[('True', 'oui'), ('False', 'non')], default='False', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
