# Generated by Django 4.2.7 on 2024-03-12 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish',
            field=models.DateField(default=datetime.datetime(2024, 3, 12, 19, 20, 56, 711389)),
        ),
    ]
